/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as OnboardingJoinRouteImport } from './routes/onboarding.join'
import { Route as OnboardingCreateRouteImport } from './routes/onboarding.create'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWishlistRouteImport } from './routes/app.wishlist'
import { Route as AppRestaurantsRouteImport } from './routes/app.restaurants'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppDiaryRouteImport } from './routes/app.diary'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/onboarding/join',
  path: '/onboarding/join',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateRoute = OnboardingCreateRouteImport.update({
  id: '/onboarding/create',
  path: '/onboarding/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/app/wishlist',
  path: '/app/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestaurantsRoute = AppRestaurantsRouteImport.update({
  id: '/app/restaurants',
  path: '/app/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/app/friends',
  path: '/app/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/app/diary',
  path: '/app/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/diary': typeof AppDiaryRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/home': typeof AppHomeRoute
  '/app/restaurants': typeof AppRestaurantsRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/diary': typeof AppDiaryRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/home': typeof AppHomeRoute
  '/app/restaurants': typeof AppRestaurantsRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/diary': typeof AppDiaryRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/home': typeof AppHomeRoute
  '/app/restaurants': typeof AppRestaurantsRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/calendar'
    | '/app/diary'
    | '/app/friends'
    | '/app/home'
    | '/app/restaurants'
    | '/app/wishlist'
    | '/auth/callback'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/calendar'
    | '/app/diary'
    | '/app/friends'
    | '/app/home'
    | '/app/restaurants'
    | '/app/wishlist'
    | '/auth/callback'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/calendar'
    | '/app/diary'
    | '/app/friends'
    | '/app/home'
    | '/app/restaurants'
    | '/app/wishlist'
    | '/auth/callback'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppRestaurantsRoute: typeof AppRestaurantsRoute
  AppWishlistRoute: typeof AppWishlistRoute
  OnboardingCreateRoute: typeof OnboardingCreateRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/onboarding/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/create': {
      id: '/onboarding/create'
      path: '/onboarding/create'
      fullPath: '/onboarding/create'
      preLoaderRoute: typeof OnboardingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/wishlist': {
      id: '/app/wishlist'
      path: '/app/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/restaurants': {
      id: '/app/restaurants'
      path: '/app/restaurants'
      fullPath: '/app/restaurants'
      preLoaderRoute: typeof AppRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/app/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/diary': {
      id: '/app/diary'
      path: '/app/diary'
      fullPath: '/app/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppHomeRoute: AppHomeRoute,
  AppRestaurantsRoute: AppRestaurantsRoute,
  AppWishlistRoute: AppWishlistRoute,
  OnboardingCreateRoute: OnboardingCreateRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
